name: .NET 6

on:
  push:
    branches: [ master ]

jobs:
  build:
    env:
      ProjectName: FileAssociations

    runs-on: windows-latest

    steps:
    - name: Clone
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Publish
      run: dotnet publish --configuration Release -p:PublishSingleFile=true --runtime win10-x64 --self-contained false
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ProjectName }}.exe
        path: ${{ env.ProjectName }}\bin\Release\**\publish\*.exe
